/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerinterdaz;

/**
 *
 * @author Erick
 */
public class FormCalcular extends javax.swing.JFrame {

    /**
     * Creates new form FormCalcular
     */
    public FormCalcular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbFiguras = new javax.swing.JComboBox<>();
        lblLado1 = new javax.swing.JLabel();
        lblLado2 = new javax.swing.JLabel();
        lblLado3 = new javax.swing.JLabel();
        txtLado1 = new javax.swing.JTextField();
        txtLado2 = new javax.swing.JTextField();
        txtLado3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblPerimetro = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbFiguras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuadrado", "Circulo", "Rectangulo", "Triangulo" }));
        cmbFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFigurasActionPerformed(evt);
            }
        });

        lblLado1.setText("Lado 1:");

        lblLado2.setText("Lado 2:");

        lblLado3.setText("Lado 3:");

        jLabel4.setText("Figura:");

        lblArea.setText("Área: ...");

        lblPerimetro.setText("Perímetro: ...");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblAltura.setText("...:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLado2)
                                .addGap(18, 18, 18)
                                .addComponent(txtLado2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLado1)
                                .addGap(18, 18, 18)
                                .addComponent(txtLado1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAltura)
                                    .addComponent(lblLado3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLado3)
                                    .addComponent(txtAltura))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblArea)
                            .addComponent(lblPerimetro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnCalcular))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado1)
                    .addComponent(txtLado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado2)
                    .addComponent(txtLado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerimetro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLado3)
                    .addComponent(txtLado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String figura = cmbFiguras.getSelectedItem().toString();
        
        String lado1 = lblLado1.getText();
        String lado2 = lblLado2.getText();
        String lado3 = lblLado3.getText();
        String altura = lblAltura.getText();
        
        //String area = lblArea.getText();
        //String perimetro = lblPerimetro.getText();
        
        Figura f1;
        
       switch (figura) {
            case "Cuadrado":
                f1 = new Cuadrado(Integer.valueOf(lado1));
                lblArea.setText(String.valueOf(f1.calcularArea()));
                lblPerimetro.setText(String.valueOf(f1.calcularPerimetro()));
                break;
            case "Rectangulo":
                f1 = new Rectangulo(Integer.valueOf(lado1), Integer.valueOf(lado2));
                lblArea.setText(String.valueOf(f1.calcularArea()));
                lblPerimetro.setText(String.valueOf(f1.calcularPerimetro()));
                break;
            case "Circulo":
                f1 = new Circulo(Integer.valueOf(lado1));
                lblArea.setText(String.valueOf(f1.calcularArea()));
                lblPerimetro.setText(String.valueOf(f1.calcularPerimetro()));
                break;
            case "Triangulo":
               f1 = new Triangulo(Integer.valueOf(lado1),Integer.valueOf(lado2), Integer.valueOf(lado3),Integer.valueOf(altura));
               lblArea.setText(String.valueOf(f1.calcularArea()));
               lblPerimetro.setText(String.valueOf(f1.calcularPerimetro()));
            default:
                break;
        }
                
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cmbFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFigurasActionPerformed
       String figura = cmbFiguras.getSelectedItem().toString();
        switch (figura) {
            case "Cuadrado":
                lblLado1.setText("Lado1:");
                lblAltura.setText("...:");
                lblLado2.setText("...:");
                lblLado3.setText("...:");
                
                txtAltura.setVisible(false);
                txtLado1.setVisible(true);
                txtLado2.setVisible(false);
                txtLado3.setVisible(false);
                break;
            case "Rectangulo":
                lblLado1.setText("Largo:");
                lblAltura.setText("...:");
                lblLado2.setText("Ancho:");
                lblLado3.setText("...:");
                
                txtAltura.setVisible(false);
                txtLado1.setVisible(true);
                txtLado2.setVisible(true);
                txtLado3.setVisible(false);
                break;
            case "Circulo":
                lblLado1.setText("Radio:");
                lblAltura.setText("...:");
                lblLado2.setText("...:");
                lblLado3.setText("...:");
                
                txtAltura.setVisible(false);
                txtLado1.setVisible(true);
                txtLado2.setVisible(false);
                txtLado3.setVisible(false);
                break;
            case "Triangulo":
                lblLado1.setText("Lado1:");
                lblAltura.setText("Altura:");
                lblLado2.setText("Lado2:");
                lblLado3.setText("Lado3:");
                
                txtAltura.setVisible(true);
                txtLado1.setVisible(true);
                txtLado2.setVisible(true);
                txtLado3.setVisible(true);
            default:
                break;
        }
    }//GEN-LAST:event_cmbFigurasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCalcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCalcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCalcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCalcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCalcular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbFiguras;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblLado1;
    private javax.swing.JLabel lblLado2;
    private javax.swing.JLabel lblLado3;
    private javax.swing.JLabel lblPerimetro;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtLado1;
    private javax.swing.JTextField txtLado2;
    private javax.swing.JTextField txtLado3;
    // End of variables declaration//GEN-END:variables
}
